#**Data Cleaning**
Work with data need of a optimate process of data preparation
 Some tools

***sed*** is a stream editor used for parsing and transforming text from input streams (like files or standard input) according to specified patterns.

***awk*** is a full-fledged programming language used primarily for pattern scanning and processing. It is especially useful for handling structured text data (like CSV, TSV, or log files).

Key Words:
* Missing dataduplicate data
* string manipulation
* analytical data transformations

## Handling Missing Data

**sentinel value**. It indic ates a missing or null value

**NOTE:** For data with float64 dtype, pandas uses the floating-point value NaN (Not a Number) to represent missing data, in contrast with strings_ dtype use none and NaN.

In [67]:
import pandas as pd
import numpy as np
float_data = pd.Series([1.2, -3.5, np.nan, 0])
float_data

0    1.2
1   -3.5
2    NaN
3    0.0
dtype: float64

In [68]:
float_data.isna()

0    False
1    False
2     True
3    False
dtype: bool

NOTE: In the R programming language by referring to missing data as NA, which stands for not available.
In statistics applications, NA data may either be data that does not exist or that exists but was not observed.

When you are cleaning up data for analysis, to do analysis on the missing data itself to identify data collection problems or potential biases in the data caused by missing data.

In [69]:
string_data = pd.Series(["aardvark", np.nan, None, "avocado"])
string_data

0    aardvark
1         NaN
2        None
3     avocado
dtype: object

In [70]:
string_data.isna()

0    False
1     True
2     True
3    False
dtype: bool

In [71]:
float_data = pd.Series([1, 2, None], dtype='float64')

In [72]:
float_data

0    1.0
1    2.0
2    NaN
dtype: float64

In [73]:
float_data.isna()

0    False
1    False
2     True
dtype: bool

## **Filtering Out Missing Data**

In [74]:
data = pd.Series([1, np.nan, 3.5, np.nan, 7])
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

###**.dropna()**

In [75]:
data.dropna()

0    1.0
2    3.5
4    7.0
dtype: float64

###**.notna()**

In [76]:
data[data.notna()]

0    1.0
2    3.5
4    7.0
dtype: float64

In [77]:
data

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

In [78]:
data = pd.DataFrame([[1., 6.5, 3.], [1., np.nan, np.nan],
 [np.nan, np.nan, np.nan], [np.nan, 6.5, 3.]])
data

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [79]:
data.dropna()
#elimimna las que tienen almenos una coincidencia NaN

     0    1    2
0  1.0  6.5  3.0

In [80]:
data.dropna(how='all')
#elimina las que en cumple con el parametro how='all'
#es decir las que cumplen con toda la fila coincidencias NaN

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
3  NaN  6.5  3.0

In [81]:
data[4] = np.nan
data

     0    1    2   4
0  1.0  6.5  3.0 NaN
1  1.0  NaN  NaN NaN
2  NaN  NaN  NaN NaN
3  NaN  6.5  3.0 NaN

**dropna(axis='columns')**

In [82]:
data.dropna(axis="columns", how="all")

     0    1    2
0  1.0  6.5  3.0
1  1.0  NaN  NaN
2  NaN  NaN  NaN
3  NaN  6.5  3.0

In [83]:
df = pd.DataFrame(np.random.standard_normal((7, 3)))

In [84]:
df

          0         1         2
0 -0.158650 -0.256511 -0.007876
1  1.695023 -0.372906 -1.119340
2 -2.033475  0.569155 -0.335848
3  0.434256 -0.180781 -0.514005
4 -0.956499 -0.546268  0.426577
5 -0.228559 -1.697656 -0.148853
6 -0.634301 -0.275626  0.432136

In [85]:
df.iloc[:4, 1] = np.nan

In [86]:
df

          0         1         2
0 -0.158650       NaN -0.007876
1  1.695023       NaN -1.119340
2 -2.033475       NaN -0.335848
3  0.434256       NaN -0.514005
4 -0.956499 -0.546268  0.426577
5 -0.228559 -1.697656 -0.148853
6 -0.634301 -0.275626  0.432136

In [87]:
df.iloc[:2, 2] = np.nan

In [88]:
df

          0         1         2
0 -0.158650       NaN       NaN
1  1.695023       NaN       NaN
2 -2.033475       NaN -0.335848
3  0.434256       NaN -0.514005
4 -0.956499 -0.546268  0.426577
5 -0.228559 -1.697656 -0.148853
6 -0.634301 -0.275626  0.432136

In [89]:
df.dropna()

          0         1         2
4 -0.956499 -0.546268  0.426577
5 -0.228559 -1.697656 -0.148853
6 -0.634301 -0.275626  0.432136

##**.dropna(thresh=numericalparameter)
thresh parameter receive a condition like a number of nan for rows or columns

In [90]:
df.dropna(thresh=2)

          0         1         2
2 -2.033475       NaN -0.335848
3  0.434256       NaN -0.514005
4 -0.956499 -0.546268  0.426577
5 -0.228559 -1.697656 -0.148853
6 -0.634301 -0.275626  0.432136

## **Filling Missing Data**

###**fillna()**

In [91]:
df.fillna(0)

          0         1         2
0 -0.158650  0.000000  0.000000
1  1.695023  0.000000  0.000000
2 -2.033475  0.000000 -0.335848
3  0.434256  0.000000 -0.514005
4 -0.956499 -0.546268  0.426577
5 -0.228559 -1.697656 -0.148853
6 -0.634301 -0.275626  0.432136

In [92]:
#you can define difeerent values using as parameter a dictionary
df.fillna({1: 0.5, 2: 0})

          0         1         2
0 -0.158650  0.500000  0.000000
1  1.695023  0.500000  0.000000
2 -2.033475  0.500000 -0.335848
3  0.434256  0.500000 -0.514005
4 -0.956499 -0.546268  0.426577
5 -0.228559 -1.697656 -0.148853
6 -0.634301 -0.275626  0.432136

In [93]:
df = pd.DataFrame(np.random.standard_normal((6, 3)))
df.iloc[2:, 1] = np.nan
df.iloc[4:, 2] = np.nan
df

          0         1         2
0  0.262539  1.317204 -0.563858
1 -0.949555 -0.363643  0.572146
2 -0.779109       NaN  0.503273
3  0.725955       NaN -1.816442
4 -0.408599       NaN       NaN
5  0.041110       NaN       NaN

####**method: ffill**

#thiso method fill the missing data with the last data

In [94]:
df.fillna(method="ffill")

<ipython-input-94-5a0d178a1f3e>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill")

          0         1         2
0  0.262539  1.317204 -0.563858
1 -0.949555 -0.363643  0.572146
2 -0.779109 -0.363643  0.503273
3  0.725955 -0.363643 -1.816442
4 -0.408599 -0.363643 -1.816442
5  0.041110 -0.363643 -1.816442

In [95]:
df.fillna(method="ffill", limit=2)

<ipython-input-95-f081c1453b62>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method="ffill", limit=2)

          0         1         2
0  0.262539  1.317204 -0.563858
1 -0.949555 -0.363643  0.572146
2 -0.779109 -0.363643  0.503273
3  0.725955 -0.363643 -1.816442
4 -0.408599       NaN -1.816442
5  0.041110       NaN -1.816442

In [96]:
data = pd.Series([1., np.nan, 3.5, np.nan, 7])
#calcula el promedio de los datos y rellena los datos vacios
data.fillna(data.mean())

0    1.000000
1    3.833333
2    3.500000
3    3.833333
4    7.000000
dtype: float64

###**parameters for fillna**

value: you can define scalar values or dictionary for fill the missing data
method:
* bfill (backward fill)
* ffill (forward fill)
* default (none)
axis:
* index
* columns
* default (index)
limit: you define with a number the consecutive periods to fill

#**Data Transformation**

##**Removing Duplicates**

In [97]:
data = pd.DataFrame({"k1": ["one", "two"] * 3 + ["two"],
                     "k2": [1, 1, 2, 3, 3, 4, 4]})
data

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4
6  two   4

###.duplicated()

In [98]:
data.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
dtype: bool

### .drop_duplicates()

In [99]:
data.drop_duplicates()

    k1  k2
0  one   1
1  two   1
2  one   2
3  two   3
4  one   3
5  two   4

In [100]:
data["v1"] = range(7)
data

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
5  two   4   5
6  two   4   6

.drop(subset=#parameter)
you can defina a column or row of analysis

In [101]:
data.drop_duplicates(subset=["k1"])

    k1  k2  v1
0  one   1   0
1  two   1   1

**keep='last'**
Both last functions, by default keep the first observed value combination. Passing keep="last" will return the last one.

In [102]:
data.drop_duplicates(["k1", "k2"], keep="last")

    k1  k2  v1
0  one   1   0
1  two   1   1
2  one   2   2
3  two   3   3
4  one   3   4
6  two   4   6

## Function or Mapping

In [103]:
data = pd.DataFrame({"food": ["bacon", "pulled pork", "bacon",
                     "pastrami", "corned beef", "bacon",
                     "pastrami", "honey ham", "nova lox"],
                     "ounces": [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

          food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     pastrami     6.0
4  corned beef     7.5
5        bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [104]:
#you define the type of meat in a dictionary
meat_to_animal = {
  "bacon": "pig",
  "pulled pork": "pig",
  "pastrami": "cow",
  "corned beef": "cow",
  "honey ham": "pig",
  "nova lox": "salmon"
}
# guardas en la columna 'animal' la agrupacion de la funcion map
#la funcion map asocia con la comida food con el diccionario.
#usa 'food' como clave al buscar en el diccionario
#guarda solo el valor definido en el diccionario
data["animal"] = data["food"].map(meat_to_animal)
data

          food  ounces  animal
0        bacon     4.0     pig
1  pulled pork     3.0     pig
2        bacon    12.0     pig
3     pastrami     6.0     cow
4  corned beef     7.5     cow
5        bacon     8.0     pig
6     pastrami     3.0     cow
7    honey ham     5.0     pig
8     nova lox     6.0  salmon

In [105]:
#this function do the same thing asthe previous one
def get_animal(x):
  return meat_to_animal[x]
data["food"].map(get_animal)

0       pig
1       pig
2       pig
3       cow
4       cow
5       pig
6       cow
7       pig
8    salmon
Name: food, dtype: object

##**Replacing Values**

In [106]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [107]:
data.replace(-999, np.nan)

0       1.0
1       NaN
2       2.0
3       NaN
4   -1000.0
5       3.0
dtype: float64

In [108]:
data.replace([-999, -1000], np.nan)

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [109]:
#Puedes asignar listas como parametros
data.replace([-999, -1000], [np.nan, 0])

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

In [110]:
#tambien puedes usar un diccionario como parametro
data.replace({-999: np.nan, -1000: 0})

0    1.0
1    NaN
2    2.0
3    NaN
4    0.0
5    3.0
dtype: float64

##**Renaming Axis Indexes**

In [111]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),
                    index=["Ohio", "Colorado", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [112]:
def transform(x):
  #this function return the first four digits of the value convert to UPPERCASE
  return x[:4].upper()
#change the index to the function agrouping the values returned by the function
data.index.map(transform)

Index(['OHIO', 'COLO', 'NEW '], dtype='object')

In [113]:
data.index = data.index.map(transform)
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

###.rename()

In [114]:
data.rename(columns=str.upper)

      ONE  TWO  THREE  FOUR
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

In [115]:
data.rename(index=str.title, columns=str.upper)

      ONE  TWO  THREE  FOUR
Ohio    0    1      2     3
Colo    4    5      6     7
New     8    9     10    11

In [116]:
data.rename(index=str.lower, columns=str.upper)

      ONE  TWO  THREE  FOUR
ohio    0    1      2     3
colo    4    5      6     7
new     8    9     10    11

In [117]:
data.rename(index={"OHIO": "INDIANA"}, columns={"three": "peekaboo"})

         one  two  peekaboo  four
INDIANA    0    1         2     3
COLO       4    5         6     7
NEW        8    9        10    11

In [118]:
data

      one  two  three  four
OHIO    0    1      2     3
COLO    4    5      6     7
NEW     8    9     10    11

##**Discretization and Binning**

###**pandas.cut()**

In [119]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
age_categories = pd.cut(ages, bins)
age_categories

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [120]:
#devuelve las posiciones a las que pertenece cada valor
age_categories.codes

array([0, 0, 0, 1, 0, 0, 2, 1, 3, 2, 2, 1], dtype=int8)

In [121]:
#devuelve los intervalos creados
age_categories.categories

IntervalIndex([(18, 25], (25, 35], (35, 60], (60, 100]], dtype='interval[int64, right]')

In [122]:
age_categories.categories[0]

Interval(18, 25, closed='right')

In [123]:
#devuelve las veces que se repiten los valores en cada intervalo
pd.value_counts(age_categories)

<ipython-input-123-eed211f460ce>:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [125]:
#devuelve las veces que aparece cada intervalo
#la consulta es diferente a la anterior
pd.value_counts(age_categories.categories)

<ipython-input-125-fc16867eb157>:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(age_categories.categories)

(18, 25]     1
(25, 35]     1
(35, 60]     1
(60, 100]    1
Name: count, dtype: int64

**Note:**
In the string representation of an interval, a parenthesis means that the side is open (exclusive), while the square bracket means it is closed (inclusive).
You can change which side is closed by passing right=False

In [126]:
pd.cut(ages, bins, right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

**atribute LABELS**

In [127]:
group_names = ["Youth", "YoungAdult", "MiddleAged", "Senior"]
pd.cut(ages, bins, labels=group_names)

['Youth', 'Youth', 'Youth', 'YoungAdult', 'Youth', ..., 'YoungAdult', 'Senior', 'MiddleAged', 'MiddleAged', 'YoungAdult']
Length: 12
Categories (4, object): ['Youth' < 'YoungAdult' < 'MiddleAged' < 'Senior']

In [129]:
type(age_categories)

pandas.core.arrays.categorical.Categorical

In [140]:
data = np.random.uniform(size=20)
#the second parameter difine the number of bines
#and the parameter precision=#number define the limit in the decimal digits
pd.cut(data, 4, precision=2)

[(0.008, 0.25], (0.008, 0.25], (0.25, 0.49], (0.25, 0.49], (0.74, 0.98], ..., (0.74, 0.98], (0.008, 0.25], (0.74, 0.98], (0.74, 0.98], (0.49, 0.74]]
Length: 20
Categories (4, interval[float64, right]): [(0.008, 0.25] < (0.25, 0.49] < (0.49, 0.74] <
                                           (0.74, 0.98]]

###**pd.qcut()**

In [141]:
data = np.random.standard_normal(1000)
quartiles = pd.qcut(data, 4, precision=2)
quartiles

[(-0.73, 0.023], (-3.5199999999999996, -0.73], (0.023, 0.68], (0.68, 2.83], (0.023, 0.68], ..., (-0.73, 0.023], (-0.73, 0.023], (-0.73, 0.023], (-3.5199999999999996, -0.73], (-0.73, 0.023]]
Length: 1000
Categories (4, interval[float64, right]): [(-3.5199999999999996, -0.73] < (-0.73, 0.023] < (0.023, 0.68] <
                                           (0.68, 2.83]]

In [142]:
pd.value_counts(quartiles)

<ipython-input-142-e680040d00da>:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(quartiles)

(-3.5199999999999996, -0.73]    250
(-0.73, 0.023]                  250
(0.023, 0.68]                   250
(0.68, 2.83]                    250
Name: count, dtype: int64

The main diference between .cut() and .qcut() is that the second cut in quantiles this make that each one have the same number of data.

In [145]:
# you can define your owns uqantiles
# in a range of 0 to 1 (like a %)
pd.qcut(data, [0, 0.1, 0.5, 0.9, 1.]).value_counts()

(-3.5149999999999997, -0.871]    200
(-0.871, 0.023]                  300
(0.023, 1.308]                   400
(1.308, 2.827]                   100
Name: count, dtype: int64

In [146]:
pd.qcut(data, [0.2, 0.6, 0.7, 0.9, 1.]).value_counts()

(-0.872, 0.273]    400
(0.273, 0.563]     100
(0.563, 1.308]     200
(1.308, 2.827]     100
Name: count, dtype: int64

##Detecting and Filtering Outliers

In [147]:
data = pd.DataFrame(np.random.standard_normal((1000, 4)))
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.098167     0.066246    -0.032137     0.035378
std       1.003832     0.957782     0.996944     0.925068
min      -3.235901    -3.049631    -3.567632    -2.691277
25%      -0.785851    -0.618086    -0.651942    -0.607068
50%      -0.129415     0.021446    -0.051323     0.046143
75%       0.579478     0.743609     0.639982     0.631758
max       3.356340     2.716147     3.691793     3.099335

**.abs()**
for absolute values

In [148]:
col = data[2]
col[col.abs() > 3]

96     3.163411
187   -3.567632
972    3.691793
Name: 2, dtype: float64

####.any() method
Define un eje al que se va a aplicar el methodo

In [150]:
data[(data.abs() > 3).any(axis="columns")]

            0         1         2         3
61  -3.235901  1.119612  0.352064  1.356583
96   0.651856 -0.385403  3.163411  0.996183
165  3.284024 -0.112022 -0.160625 -0.085257
187 -0.057674  0.422806 -3.567632  1.273512
370 -0.125592 -0.046909  1.509382  3.099335
381 -0.776933 -3.049631 -0.554907 -1.354552
463  3.166001  0.247963 -0.396018  1.675151
813  3.356340  0.837431  1.345609 -0.773848
972 -0.285218 -0.928374  3.691793  0.253363

In [157]:
data[data.abs() > 3] = np.sign(data) * 3
#np.sign devuelve el signo de cada dato (1,-1,0)
data.describe()

                 0            1            2            3
count  1000.000000  1000.000000  1000.000000  1000.000000
mean     -0.098737     0.066295    -0.032424     0.035278
std       1.000507     0.957622     0.992223     0.924744
min      -3.000000    -3.000000    -3.000000    -2.691277
25%      -0.785851    -0.618086    -0.651942    -0.607068
50%      -0.129415     0.021446    -0.051323     0.046143
75%       0.579478     0.743609     0.639982     0.631758
max       3.000000     2.716147     3.000000     3.000000

In [160]:
data[(data.abs() >= 3).any(axis="columns")]

            0         1         2         3
61  -3.000000  1.119612  0.352064  1.356583
96   0.651856 -0.385403  3.000000  0.996183
165  3.000000 -0.112022 -0.160625 -0.085257
187 -0.057674  0.422806 -3.000000  1.273512
370 -0.125592 -0.046909  1.509382  3.000000
381 -0.776933 -3.000000 -0.554907 -1.354552
463  3.000000  0.247963 -0.396018  1.675151
813  3.000000  0.837431  1.345609 -0.773848
972 -0.285218 -0.928374  3.000000  0.253363

### .sign()

In [161]:
np.sign(data).head()

     0    1    2    3
0  1.0  1.0  1.0 -1.0
1 -1.0  1.0  1.0  1.0
2 -1.0  1.0 -1.0  1.0
3 -1.0 -1.0 -1.0 -1.0
4 -1.0 -1.0  1.0  1.0

#Permutation and Random Samplling
Permuting (randomly reordering) a Series or the rows in a DataFrame is possible using the numpy.random.permutation function. Calling permutation with the length of the axis you want to permute produces an array of integers indicating the new ordering

In [162]:
df = pd.DataFrame(np.arange(5 * 7).reshape((5, 7)))
df

    0   1   2   3   4   5   6
0   0   1   2   3   4   5   6
1   7   8   9  10  11  12  13
2  14  15  16  17  18  19  20
3  21  22  23  24  25  26  27
4  28  29  30  31  32  33  34

### .permutation(number)

In [163]:
#devuelve una combinacion
sampler = np.random.permutation(5)
sampler

array([2, 4, 1, 3, 0])

###.take()

In [164]:
#present in order to sampler
df.take(sampler)

    0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6

In [165]:
 #do the same thing that .take()
 df.iloc[sampler]

    0   1   2   3   4   5   6
2  14  15  16  17  18  19  20
4  28  29  30  31  32  33  34
1   7   8   9  10  11  12  13
3  21  22  23  24  25  26  27
0   0   1   2   3   4   5   6

In [166]:
column_sampler = np.random.permutation(7)
column_sampler

array([6, 1, 3, 0, 4, 2, 5])

In [167]:
df.take(column_sampler, axis="columns")

    6   1   3   0   4   2   5
0   6   1   3   0   4   2   5
1  13   8  10   7  11   9  12
2  20  15  17  14  18  16  19
3  27  22  24  21  25  23  26
4  34  29  31  28  32  30  33

###.sample()
To select a random subset without replacement (the same row cannot appear twice), you can use the sample method on Series and DataFrame

In [168]:
df.sample(n=3)

    0   1   2   3   4   5   6
4  28  29  30  31  32  33  34
2  14  15  16  17  18  19  20
0   0   1   2   3   4   5   6

In [169]:
choices = pd.Series([5, 7, -1, 6, 4])
#argument replace=true allow repeat data
choices.sample(n=10, replace=True)

1    7
3    6
4    4
0    5
3    6
0    5
4    4
2   -1
0    5
4    4
dtype: int64

##Computing Indicator/Dummy Variables
Key Words: dummy or indicator matrix

**Dummy Variables**. It is a binary (0 or 1) variable created to represent categorical data as numerical data.

**Indicator matrix**.  Typically refers to a matrix of binary values (0 or 1), where each row corresponds to an observation, and each column corresponds to a specific category or feature. It "indicates" the presence or absence of a particular characteristic.

If a column in a DataFrame has k distinct values, you would derive a matrix or DataFrame with k columns containing all 1s and 0s. pandas has a pandas.get_dummies function for doing this

In [171]:
df = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                    "data1": range(6)})
df

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

###pd.get_dummies

In [172]:
pd.get_dummies(df["key"], dtype=float)

     a    b    c
0  0.0  1.0  0.0
1  0.0  1.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  1.0  0.0  0.0
5  0.0  1.0  0.0

In [173]:
pd.get_dummies(df["key"])

       a      b      c
0  False   True  False
1  False   True  False
2   True  False  False
3  False  False   True
4   True  False  False
5  False   True  False

In [174]:
pd.get_dummies(df["key"], dtype=int)

   a  b  c
0  0  1  0
1  0  1  0
2  1  0  0
3  0  0  1
4  1  0  0
5  0  1  0

####.join()
this add a prefix

In [175]:
dummies = pd.get_dummies(df["key"], prefix="key", dtype=float)
df_with_dummy = df[["data1"]].join(dummies)
df_with_dummy

   data1  key_a  key_b  key_c
0      0    0.0    1.0    0.0
1      1    0.0    1.0    0.0
2      2    1.0    0.0    0.0
3      3    0.0    0.0    1.0
4      4    1.0    0.0    0.0
5      5    0.0    1.0    0.0

In [178]:
mnames = ["movie_id", "title", "genres"]
movies = pd.read_table("examples/movies.dat", sep="::",
                       header=None, names=mnames, engine="python")
movies[:10]

   movie_id                               title                        genres
0         1                    Toy Story (1995)   Animation|Children's|Comedy
1         2                      Jumanji (1995)  Adventure|Children's|Fantasy
2         3             Grumpier Old Men (1995)                Comedy|Romance
3         4            Waiting to Exhale (1995)                  Comedy|Drama
4         5  Father of the Bride Part II (1995)                        Comedy
5         6                         Heat (1995)         Action|Crime|Thriller
6         7                      Sabrina (1995)                Comedy|Romance
7         8                 Tom and Huck (1995)          Adventure|Children's
8         9                 Sudden Death (1995)                        Action
9        10                    GoldenEye (1995)     Action|Adventure|Thriller

###str.get_dummies()

In [179]:
#primero toma solo la columna 'genres'
#crea la matriz con los string de esa columns
#los distingue por el caracter|
dummies = movies["genres"].str.get_dummies("|")
dummies.iloc[:10, :6]

   Action  Adventure  Animation  Children's  Comedy  Crime
0       0          0          1           1       1      0
1       0          1          0           1       0      0
2       0          0          0           0       1      0
3       0          0          0           0       1      0
4       0          0          0           0       1      0
5       1          0          0           0       0      1
6       0          0          0           0       1      0
7       0          1          0           1       0      0
8       1          0          0           0       0      0
9       1          1          0           0       0      0

In [181]:
movies_windic = movies.join(dummies.add_prefix("Genre_"))
movies_windic.iloc[2]

movie_id                                   3
title                Grumpier Old Men (1995)
genres                        Comedy|Romance
Genre_Action                               0
Genre_Adventure                            0
Genre_Animation                            0
Genre_Children's                           0
Genre_Comedy                               1
Genre_Crime                                0
Genre_Documentary                          0
Genre_Drama                                0
Genre_Fantasy                              0
Genre_Film-Noir                            0
Genre_Horror                               0
Genre_Musical                              0
Genre_Mystery                              0
Genre_Romance                              1
Genre_Sci-Fi                               0
Genre_Thriller                             0
Genre_War                                  0
Genre_Western                              0
Name: 2, dtype: object

In [184]:
# to make the example repeatable
#semilla
np.random.seed(12345)
values = np.random.uniform(size=10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [186]:
np.random.seed(12345)
values = np.random.uniform(size=10)
values

array([0.92961609, 0.31637555, 0.18391881, 0.20456028, 0.56772503,
       0.5955447 , 0.96451452, 0.6531771 , 0.74890664, 0.65356987])

In [187]:
bins = [0, 0.2, 0.4, 0.6, 0.8, 1]
pd.get_dummies(pd.cut(values, bins))

   (0.0, 0.2]  (0.2, 0.4]  (0.4, 0.6]  (0.6, 0.8]  (0.8, 1.0]
0       False       False       False       False        True
1       False        True       False       False       False
2        True       False       False       False       False
3       False        True       False       False       False
4       False       False        True       False       False
5       False       False        True       False       False
6       False       False       False       False        True
7       False       False       False        True       False
8       False       False       False        True       False
9       False       False       False        True       False

#Extension Data Types

Main
* Missing data handling for some numerical data types, such as integers and Booleans, was incomplete.

* Datasets with a lot of string data were computationally expensive and used a lot of memory.

* Some data types, like time intervals, timedeltas, and timestamps with time zones, could not be supported efficiently without using computationally expensive arrays of Python objects.

In [188]:
s = pd.Series([1, 2, 3, None])
s

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64

In [189]:
#pandas usually convert to float
s.dtype

dtype('float64')

In [190]:
s = pd.Series([1, 2, 3, None], dtype=pd.Int64Dtype())
s

0       1
1       2
2       3
3    <NA>
dtype: Int64

In [191]:
s.isna()

0    False
1    False
2    False
3     True
dtype: bool

In [192]:
s[3]

In [194]:
s[3] is pd.NA

True

In [195]:
s = pd.Series(['one', 'two', None, 'three'], dtype=pd.StringDtype())
s

0      one
1      two
2     <NA>
3    three
dtype: string

### .astype() Categorical

In [196]:
df = pd.DataFrame({"A": [1, 2, None, 4],
                   "B": ["one", "two", "three", None],
                   "C": [False, None, False, True]})
df

     A      B      C
0  1.0    one  False
1  2.0    two   None
2  NaN  three  False
3  4.0   None   True

In [197]:
df["A"] = df["A"].astype("Int64")
df["B"] = df["B"].astype("string")
df["C"] = df["C"].astype("boolean")
df

      A      B      C
0     1    one  False
1     2    two   <NA>
2  <NA>  three  False
3     4   <NA>   True

#String Manipulation
Python has long been a popular raw data manipulation language in part due to its ease of use for string and text processing.
##Python Built-In String Object Methods

##.split()
Separate

In [199]:
val = "a,b,  guido"
val.split(",")

['a', 'b', '  guido']

###.strip()
elimina espacion en blanco o caracteres especificados al principio y final de la cadena

In [200]:
pieces = [x.strip() for x in val.split(",")]
pieces

['a', 'b', 'guido']

In [201]:
first, second, third = pieces
first + "::" + second + "::" + third

'a::b::guido'

In [202]:
"guido" in val

True

###.index()

In [203]:
val.index(",")

1

###.find()

In [204]:
val.find(":")

-1

Note that the difference between find and index is that index raises an exception if the string isn’t found (versus returning –1)

In [205]:
val.index(":")

ValueError: substring not found

In [206]:
 val.count(",")

2

###.replace()

In [207]:
val.replace(",", "::")

'a::b::  guido'

In [208]:
val.replace(",", "")

'ab  guido'

##Regular Expressions

Regular expressions provide a flexible way to search or match (often more complex) string patterns in text.

##re module
The re module functions fall into three categories: pattern matching, substitution, and splitting.

##.regex()
Naturally these are all related; a regex describes a pattern to locate in the text, which can then be used for many purposes.

In [209]:
import re
text = "foo    bar\t baz  \tqux"
re.split(r"\s+", text)

['foo', 'bar', 'baz', 'qux']