#**Data Loading**
Reading data and making it accessible is a necessary first step for using most of the tools in this book.

**Parsing**
 The term parsing is also sometimes used to describe loading text data and interpreting it as tables and different data types.

**Indexing**
Can treat one or more columns as the returned DataFrame, and whether to get column names from the file, arguments you provide, or not at all.

**Type inference and data conversion**
Includes the user-defined value conversions and custom list of missing value markers.

**Date and time parsing**
Includes a combining capability, including combining date and time information spread over multiple columns into a single column in the result.

**Iterating**
Support for iterating over chunks of very large files.

**Unclean data issues**
Includes skipping rows or a footer, comments, or other minor things like numeric data with thousands separated by commas.

In [2]:
import pandas as pd

In [3]:
!cat examples/ex1.csv

a,b,c,d,message
1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

**cat** Unix cat shell command to print the raw contents of the file to the screen.

In [4]:
df = pd.read_csv("examples/ex1.csv")
df

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

###**.read_csv()**
change de ','

In [5]:
!cat examples/ex2.csv

1,2,3,4,hello
5,6,7,8,world
9,10,11,12,foo

In [6]:
pd.read_csv("examples/ex2.csv", header=None)

   0   1   2   3      4
0  1   2   3   4  hello
1  5   6   7   8  world
2  9  10  11  12    foo

In [7]:
pd.read_csv("examples/ex2.csv", names=["a", "b", "c", "d", "message"])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

In [8]:
names = ["a", "b", "c", "d", "message"]
pd.read_csv("examples/ex2.csv", names=names, index_col="message")

         a   b   c   d
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

### **.index_col()**
this parametre is the new index of this data frame, you need especific the index of the column or the name of the column

In [9]:
!cat examples/csv_mindex.csv

key1,key2,value1,value2
one,a,1,2
one,b,3,4
one,c,5,6
one,d,7,8
two,a,9,10
two,b,11,12
two,c,13,14
two,d,15,16

In [10]:
pd.read_csv("examples/csv_mindex.csv",index_col=["key1", "key2"])

           value1  value2
key1 key2
one  a          1       2
     b          3       4
     c          5       6
     d          7       8
two  a          9      10
     b         11      12
     c         13      14
     d         15      16

In [11]:
!cat examples/ex3.txt

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

** \\s+**
property for change the whitespace and convert the information to data **frame**

In [12]:
pd.read_csv("examples/ex3.txt", sep="\s+")

            A         B         C
aaa -0.264438 -1.026059 -0.619500
bbb  0.927272  0.302904 -0.032399
ccc -0.264273 -0.386314 -0.217601
ddd -0.871858 -0.348382  1.100491

**skiprows**

In [13]:
pd.read_csv("examples/ex4.csv")

                                                                      # hey!
a                                                  b        c   d    message
# just wanted to make things more difficult for... NaN      NaN NaN      NaN
# who reads CSV files with computers                anyway? NaN NaN      NaN
1                                                  2        3   4      hello
5                                                  6        7   8      world
9                                                  10       11  12       foo

In [14]:
pd.read_csv("examples/ex4.csv", skiprows=[0, 2, 3])

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

**NAN and NULL** Missing data is usually either not present (empty string) or marked by some sentinel (placeholder) value

In [15]:
!cat examples/ex5.csv
ex5=pd.read_csv("examples/ex5.csv")
ex5

something,a,b,c,d,message
one,1,2,3,4,NA
two,5,6,,8,world
three,9,10,11,12,foo

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

**.isna()**

In [16]:
pd.isna(ex5)

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False   True  False    False
2      False  False  False  False  False    False

**na_values=''** for replace NAN for something else

In [17]:
result = pd.read_csv("examples/ex5.csv", na_values=["Ana"])
result

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

**keep_default_na=false**
you can delete the default funcion for NAN

In [18]:
result2 = pd.read_csv("examples/ex5.csv", keep_default_na=False)
result2

  something  a   b   c   d message
0       one  1   2   3   4      NA
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [19]:
result2.isna()

   something      a      b      c      d  message
0      False  False  False  False  False    False
1      False  False  False  False  False    False
2      False  False  False  False  False    False

In [20]:
result3 = pd.read_csv("examples/ex5.csv", keep_default_na=False, na_values=["NA"])
result3

  something  a   b   c   d message
0       one  1   2   3   4     NaN
1       two  5   6       8   world
2     three  9  10  11  12     foo

In [21]:
result3.isna()

   something      a      b      c      d  message
0      False  False  False  False  False     True
1      False  False  False  False  False    False
2      False  False  False  False  False    False

*Cuando usas keep_default_na=False, Pandas no convierte automáticamente los valores como NA en NaN. Esto significa que la cadena "NA" en la columna message no es reconocida como un valor nulo y, por lo tanto, no se marca como NaN (lo que resulta en False cuando verificas si es NaN con isna()).

# Reading text files in Pieces

In [22]:
#Reading text files in PIeces

In [23]:
pd.options.display.max_rows = 15
#it is a limit

In [24]:
result = pd.read_csv("examples/ex6.csv")
result

           one       two     three      four key
0     0.467976 -0.038649 -0.295344 -1.824726   L
1    -0.358893  1.404453  0.704965 -0.200638   B
2    -0.501840  0.659254 -0.421691 -0.057688   G
3     0.204886  1.074134  1.388361 -0.982404   R
4     0.354628 -0.133116  0.283763 -0.837063   Q
...        ...       ...       ...       ...  ..
9995  2.311896 -0.417070 -1.409599 -0.515821   L
9996 -0.479893 -0.650419  0.745152 -0.646038   E
9997  0.523331  0.787112  0.486066  1.093156   K
9998 -0.362559  0.598894 -1.843201  0.887292   G
9999 -0.096376 -1.012999 -0.657431 -0.573315   0

[10000 rows x 5 columns]

**nrows**, just show a determinate number of rows

In [25]:
pd.read_csv("examples/ex6.csv", nrows=3)

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G

**chunksize**, cut the file in a determinate number of (chunks)

In [26]:
chunker = pd.read_csv("examples/ex6.csv", chunksize=10)
type(chunker)

pandas.io.parsers.readers.TextFileReader

In [27]:
chunker = pd.read_csv("examples/ex6.csv", chunksize=1000)

tot = pd.Series([], dtype='int64')
for piece in chunker:
    tot = tot.add(piece["key"].value_counts(), fill_value=0)

tot = tot.sort_values(ascending=False)

In [28]:
tot[:10]

key
E    368.0
X    364.0
L    346.0
O    343.0
Q    340.0
M    338.0
J    337.0
F    335.0
K    334.0
H    330.0
dtype: float64

In [29]:
tot[:1]

key
E    368.0
dtype: float64

**get_chunk**, just print the number of rows determinated

In [30]:
chunk = pd.read_csv("examples/ex6.csv", chunksize=10)
chun= chunk.get_chunk(5)
chun

        one       two     three      four key
0  0.467976 -0.038649 -0.295344 -1.824726   L
1 -0.358893  1.404453  0.704965 -0.200638   B
2 -0.501840  0.659254 -0.421691 -0.057688   G
3  0.204886  1.074134  1.388361 -0.982404   R
4  0.354628 -0.133116  0.283763 -0.837063   Q

# Writing Data to Text Format

In [31]:
data = pd.read_csv("examples/ex5.csv")
data

  something  a   b     c   d message
0       one  1   2   3.0   4     NaN
1       two  5   6   NaN   8   world
2     three  9  10  11.0  12     foo

## **.to_csv()**
this transform data to a file .csv, just need put the name of file as parameter

In [32]:
data.to_csv("examples/out.csv")
!cat examples/out.csv

,something,a,b,c,d,message
0,one,1,2,3.0,4,
1,two,5,6,,8,world
2,three,9,10,11.0,12,foo

# Sys (module)
This librarie have an focus on functions and variables and them mood of interact with the operative system.

##**sys.stdout**
this function, define the standard out like a template

In [33]:
import sys
data.to_csv(sys.stdout, sep="|")

|something|a|b|c|d|message
0|one|1|2|3.0|4|
1|two|5|6||8|world
2|three|9|10|11.0|12|foo

In [34]:
data.to_csv(sys.stdout, na_rep="NULL")

,something,a,b,c,d,message
0,one,1,2,3.0,4,NULL
1,two,5,6,NULL,8,world
2,three,9,10,11.0,12,foo

In [35]:
data.to_csv(sys.stdout, index=False, header=False)

one,1,2,3.0,4,
two,5,6,,8,world
three,9,10,11.0,12,foo

In [36]:
data.to_csv(sys.stdout, index=False, columns=["a", "b", "c"])

a,b,c
1,2,3.0
5,6,
9,10,11.0

# Working with other delimited formats

In [37]:
!cat examples/ex7.csv

"a","b","c"
"1","2","3"
"1","2","3"

# librarie vs module
Sometimes we can use both words for the same concept but the main diference is that a **module** is just an file with code, that could have functions, class and variables,  (the format is .py).

In contrast a **librarie** is  a set  of modules of biggest size..

##**csv(module)**

In [38]:
import csv
f= open("examples/ex7.csv")
reader = csv.reader(f)

In [39]:
for line in reader:
  print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [40]:
f.close()

**.open()**
You must open the file

**.close()**
And you should close the file

In [41]:
reader

For read a file you need move in lines of code this module recognize line breaks

###**csv.reader**

In [42]:
with open("examples/ex7.csv") as f:
  lines = list(csv.reader(f))

In [43]:
header, values = lines[0], lines[1:]

In [44]:
data_dict = {h: v for h, v in zip(header, zip(*values))}
data_dict

{'a': ('1', '1'), 'b': ('2', '2'), 'c': ('3', '3')}

**reminder** zip() function compress two or more list of data

###**zip(*)**
 zip(*values) (beware that this will use a lot of memory on large files), which transposes rows to columns

In [45]:
header

['a', 'b', 'c']

In [46]:
values

[['1', '2', '3'], ['1', '2', '3']]

In [47]:
lines

[['a', 'b', 'c'], ['1', '2', '3'], ['1', '2', '3']]

###**csv.Dialect**
To define a new format with a different delimiter, string quoting convention, or line terminator, we could define a simple subclass of csv.Dialect

In [48]:
class my_dialect(csv.Dialect):
    lineterminator = "\n"
    delimiter = ";"
    quotechar = '"'
    quoting = csv.QUOTE_MINIMAL

In [49]:
f= open("examples/ex7.csv")
r=csv.reader(f)
for line in r:
  print(line)

['a', 'b', 'c']
['1', '2', '3']
['1', '2', '3']

In [50]:
f= open("examples/ex7.csv")
r1=csv.reader(f, dialect=my_dialect)
for line in r1:
  print(line)

['a,"b","c"']
['1,"2","3"']
['1,"2","3"']

In [51]:
f= open("examples/ex7.csv")
f1=f.read()
f2=f1.replace(',','|')
r2= csv.reader(f2, delimiter="|")
for line in r2:
  print(line)

['a']
['', '']
['b']
['', '']
['c']
[]
['1']
['', '']
['2']
['', '']
['3']
[]
['1']
['', '']
['2']
['', '']
['3']
[]

###**split**
this method separate an string to a char with and delimiter as parameter

In [52]:
a='a,n,a'
b=a.split(',')
b

['a', 'n', 'a']

### **re.split**
It is similar to split, but this method accept a delimiter pattern

You need import the module **re**

In [53]:
import re
a='a;n,a:p,a:u;l;a'
b=re.split(r'[;,:]',a)
b

['a', 'n', 'a', 'p', 'a', 'u', 'l', 'a']

### **csv.writer**

In [54]:
with open("examples/mydata.csv", "w") as f:
    writer = csv.writer(f, dialect=my_dialect)
    writer.writerow(("one", "two", "three"))
    writer.writerow(("1", "2", "3"))
    writer.writerow(("4", "5", "6"))
    writer.writerow(("7", "8", "9"))

In [55]:
f=open("examples/mydata.csv")
for l in f:
  print(l)

one;two;three

1;2;3

4;5;6

7;8;9

## JSON Data
Is an standard format for ending data by HTTP

In [56]:
obj = """
{"name": "Wes",
 "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"],
 "pet": null,
 "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]},
              {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]
}
"""

JSON is very nearly valid Python code with the exception of its null value null

All of the keys in an object must be strings.
JSON format is like a string

## **JSON (librarie)**

### **.load()**
Is for transform data in JSON format to Python data

In [57]:
import json
result=json.loads(obj)
result

{'name': 'Wes',
 'cities_lived': ['Akron', 'Nashville', 'New York', 'San Francisco'],
 'pet': None,
 'siblings': [{'name': 'Scott', 'age': 34, 'hobbies': ['guitars', 'soccer']},
  {'name': 'Katie', 'age': 42, 'hobbies': ['diving', 'art']}]}

###**.dumps()**
Is for transform python data in JSON format

In [58]:
json.dumps(result)

'{"name": "Wes", "cities_lived": ["Akron", "Nashville", "New York", "San Francisco"], "pet": null, "siblings": [{"name": "Scott", "age": 34, "hobbies": ["guitars", "soccer"]}, {"name": "Katie", "age": 42, "hobbies": ["diving", "art"]}]}'

In [59]:
siblings = pd.DataFrame(result["siblings"], columns=["name", "age"])
siblings

    name  age
0  Scott   34
1  Katie   42

##**pandas.read_json()**
It can automatically convert JSON datasets in specific arrangements into a Series or DataFrame

In [60]:
!cat examples/example.json

[{"a": 1, "b": 2, "c": 3},
 {"a": 4, "b": 5, "c": 6},
 {"a": 7, "b": 8, "c": 9}]

In [61]:
data=pd.read_json("examples/example.json")
data

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

##**.to_json()**
For convert of python data to JOSN format

In [62]:
data.to_json(sys.stdout)

{"a":{"0":1,"1":4,"2":7},"b":{"0":2,"1":5,"2":8},"c":{"0":3,"1":6,"2":9}}

In [63]:
data.to_json(sys.stdout, orient="records")

[{"a":1,"b":2,"c":3},{"a":4,"b":5,"c":6},{"a":7,"b":8,"c":9}]

#XML and HTML : Web Scraping

Some libraries for read data in this formats are lxml, beautiful soup, html5lib

In [64]:
pip install lxml

Requirement already satisfied: lxml in /usr/local/lib/python3.11/dist-packages (5.3.1)

##**pandas.read_html**

In [65]:
tables = pd.read_html("examples/fdic_failed_bank_list.html")
len(tables)

1

In [66]:
failures = tables[0]
failures.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [67]:
failures['Bank Name']

0                            Allied Bank
1           The Woodbury Banking Company
2                 First CornerStone Bank
3                     Trust Company Bank
4             North Milwaukee State Bank
                     ...
542                   Superior Bank, FSB
543                  Malta National Bank
544      First Alliance Bank & Trust Co.
545    National State Bank of Metropolis
546                     Bank of Honolulu
Name: Bank Name, Length: 547, dtype: object

In [68]:
failures[:2]

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"

In [69]:
failures[:2]

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"

In [70]:
failures.iloc[0:3]

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"

In [71]:
failures.loc[0:2,'Bank Name']

0                     Allied Bank
1    The Woodbury Banking Company
2          First CornerStone Bank
Name: Bank Name, dtype: object

In [72]:
failures.head()

,Bank Name,City,ST,CERT,Acquiring Institution,Closing Date,Updated Date
0,Allied Bank,Mulberry,AR,91,Today's Bank,"September 23, 2016","November 17, 2016"
1,The Woodbury Banking Company,Woodbury,GA,11297,United Bank,"August 19, 2016","November 17, 2016"
2,First CornerStone Bank,King of Prussia,PA,35312,First-Citizens Bank & Trust Company,"May 6, 2016","September 6, 2016"
3,Trust Company Bank,Memphis,TN,9956,The Bank of Fayette County,"April 29, 2016","September 6, 2016"
4,North Milwaukee State Bank,Milwaukee,WI,20364,First-Citizens Bank & Trust Company,"March 11, 2016","June 16, 2016"

In [73]:
#this covert the data with the column closing date to format date time
#because in the next line, we need that this data are in time format
close_timestamps = pd.to_datetime(failures["Closing Date"])
#Ask for how many coincidence have this data about year
close_timestamps.dt.year.value_counts()

Closing Date
2010    157
2009    140
2011     92
2012     51
2008     25
2013     24
2014     18
2002     11
2015      8
2016      5
2004      4
2001      4
2007      3
2003      3
2000      2
Name: count, dtype: int64

##**XML** (Extensible Markup Language)

###**Parsing XML with lxml.objectify**
The xml file have a type of structure data, where each data have a determinate sort that use python for transform data to dataframes or series, using tags for assign the order

##**lxml.objectify (librarie)**

###**objectify.parse()**
This transform the data to data readable by python

In [74]:
from lxml import objectify
path = "examples/Performance_MNR.xml"
with open(path) as f:
  parsed = objectify.parse(f)

### **.getroot()**
this save the main root of the file

In [75]:
root = parsed.getroot()
root

In [76]:
root.INDICATOR

In [77]:
data = []
#here assign in a list the name of columns that will be ignore
skip_fields = ["PARENT_SEQ", "INDICATOR_SEQ",
               "DESIRED_CHANGE", "DECIMAL_PLACES"]
#este ciclo recorre las secciones en la rama principal
for elt in root.INDICATOR:
  #define un diccionario para agregar datos luego
    el_data = {}
    #este ciclo recorre los elementos hijo de la rama principal
    for child in elt.getchildren():
      #compara la etiqueta de las columnas con las que se iban a ignorar
        if child.tag in skip_fields:
          #en casso de encontrarse coincidencia sale del bucle
            continue
            #caso contrario asigna al diccionario los valores
        el_data[child.tag] = child.pyval
        #finalmente agrega el diccionario a la lista data
    data.append(el_data)

el_data

{'AGENCY_NAME': 'Metro-North Railroad',
 'INDICATOR_NAME': 'Escalator Availability',
 'DESCRIPTION': 'Percent of the time that escalators are operational systemwide. The availability rate is based on physical observations performed the morning of regular business days only. This is a new indicator the agency began reporting in 2009.',
 'PERIOD_YEAR': 2011,
 'PERIOD_MONTH': 12,
 'CATEGORY': 'Service Indicators',
 'FREQUENCY': 'M',
 'INDICATOR_UNIT': '%',
 'YTD_TARGET': 97.0,
 'YTD_ACTUAL': '',
 'MONTHLY_TARGET': 97.0,
 'MONTHLY_ACTUAL': ''}

In [78]:
pf=pd.DataFrame(data)
pf.head()

,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,INDICATOR_UNIT,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,%,95.0,96.9,95.0,96.9
1,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,%,95.0,96.0,95.0,95.0
2,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,%,95.0,96.3,95.0,96.9
3,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,%,95.0,96.8,95.0,98.3
4,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,%,95.0,96.6,95.0,95.8

In [80]:
data[0]

{'AGENCY_NAME': 'Metro-North Railroad',
 'INDICATOR_NAME': 'On-Time Performance (West of Hudson)',
 'DESCRIPTION': 'Percent of commuter trains that arrive at their destinations within 5 minutes and 59 seconds of the scheduled time. West of Hudson services include the Pascack Valley and Port Jervis lines. Metro-North Railroad contracts with New Jersey Transit to operate service on these lines.\n',
 'PERIOD_YEAR': 2008,
 'PERIOD_MONTH': 1,
 'CATEGORY': 'Service Indicators',
 'FREQUENCY': 'M',
 'INDICATOR_UNIT': '%',
 'YTD_TARGET': 95.0,
 'YTD_ACTUAL': 96.9,
 'MONTHLY_TARGET': 95.0,
 'MONTHLY_ACTUAL': 96.9}

### **pandas.read_xml()**
(This function is a short form to the last code)

In [81]:
perf2 = pd.read_xml(path)
perf2.head()

,INDICATOR_SEQ,PARENT_SEQ,AGENCY_NAME,INDICATOR_NAME,DESCRIPTION,PERIOD_YEAR,PERIOD_MONTH,CATEGORY,FREQUENCY,DESIRED_CHANGE,INDICATOR_UNIT,DECIMAL_PLACES,YTD_TARGET,YTD_ACTUAL,MONTHLY_TARGET,MONTHLY_ACTUAL
0,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,1,Service Indicators,M,U,%,1,95.00,96.90,95.00,96.90
1,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,2,Service Indicators,M,U,%,1,95.00,96.00,95.00,95.00
2,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,3,Service Indicators,M,U,%,1,95.00,96.30,95.00,96.90
3,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,4,Service Indicators,M,U,%,1,95.00,96.80,95.00,98.30
4,28445,NaN,Metro-North Railroad,On-Time Performance (West of Hudson),Percent of commuter trains that arrive at thei...,2008,5,Service Indicators,M,U,%,1,95.00,96.60,95.00,95.80

#**Binary Data Formats**

In [82]:
frame = pd.read_csv("examples/ex1.csv")
frame

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

###**.to_pickle()**
This convert anay object to a data binary format

In [83]:
frame.to_pickle("examples/frame_pickle")

###**pandas.read_pickle**
This function transform binary data to a readable data by python

In [84]:
#no puedes abir archivos en formato pickle con funciones formato text
pd.read_pickle("examples/frame_pickle")

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

### **Pickle**
Advice: Use just like a short-term storage format
This because problems with compatibility about versions

####**Note:**
Pandas has built-in support for several other open source binary data formats, such as HDF5, ORC, and Apache Parquet. For example, if you install the pyarrow package (conda install pyarrow), then you can read Parquet files with pandas.read_parquet

###**pandaas.read_parquet()**
This read a binary data format to a format reable by python

In [97]:
fec = pd.read_parquet('examples/fec.parquet')
fec

,cmte_id,cand_id,cand_nm,contbr_nm,contbr_city,contbr_st,contbr_zip,contbr_employer,contbr_occupation,contb_receipt_amt,contb_receipt_dt,receipt_desc,memo_cd,memo_text,form_tp,file_num
0,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,366010290,RETIRED,RETIRED,250.0,20-JUN-11,None,None,None,SA17A,736166
1,C00410118,P20002978,"Bachmann, Michelle","HARVEY, WILLIAM",MOBILE,AL,366010290,RETIRED,RETIRED,50.0,23-JUN-11,None,None,None,SA17A,736166
2,C00410118,P20002978,"Bachmann, Michelle","SMITH, LANIER",LANETT,AL,368633403,INFORMATION REQUESTED,INFORMATION REQUESTED,250.0,05-JUL-11,None,None,None,SA17A,749073
3,C00410118,P20002978,"Bachmann, Michelle","BLEVINS, DARONDA",PIGGOTT,AR,724548253,NONE,RETIRED,250.0,01-AUG-11,None,None,None,SA17A,749073
4,C00410118,P20002978,"Bachmann, Michelle","WARDENBURG, HAROLD",HOT SPRINGS NATION,AR,719016467,NONE,RETIRED,300.0,20-JUN-11,None,None,None,SA17A,736166
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1001726,C00500587,P20003281,"Perry, Rick","GORMAN, CHRIS D. MR.",INFO REQUESTED,XX,99999,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,5000.0,29-SEP-11,REATTRIBUTION / REDESIGNATION REQUESTED (AUTOM...,None,REATTRIBUTION / REDESIGNATION REQUESTED (AUTOM...,SA17A,751678
1001727,C00500587,P20003281,"Perry, Rick","DUFFY, DAVID A. MR.",INFO REQUESTED,XX,99999,DUFFY EQUIPMENT COMPANY INC.,BUSINESS OWNER,2500.0,30-SEP-11,None,None,None,SA17A,751678
1001728,C00500587,P20003281,"Perry, Rick","GRANE, BRYAN F. MR.",INFO REQUESTED,XX,99999,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,500.0,29-SEP-11,None,None,None,SA17A,751678
1001729,C00500587,P20003281,"Perry, Rick","TOLBERT, DARYL MR.",INFO REQUESTED,XX,99999,T.A.C.C.,LONGWALL MAINTENANCE FOREMAN,500.0,30-SEP-11,None,None,None,SA17A,751678
1001730,C00500587,P20003281,"Perry, Rick","ANDERSON, MARILEE MRS.",INFO REQUESTED,XX,99999,INFORMATION REQUESTED PER BEST EFFORTS,INFORMATION REQUESTED PER BEST EFFORTS,2500.0,31-AUG-11,None,None,None,SA17A,751678

##Reading Microsoft Excel Files

###**.ExcelFile()**

In [99]:
xlsx = pd.ExcelFile("examples/ex1.xlsx")
xlsx

In [100]:
xlsx.sheet_names

['Sheet1']

####**xlsx.parse()**
This read a sheet in excel format

In [101]:
xlsx.parse(sheet_name="Sheet1")

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

In [102]:
xlsx.parse(sheet_name="Sheet1", index_col=0)

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12     foo

###**pandas.read_excel()**
this function is most recommendable if you have a file with just one sheet

In [104]:
pd.read_excel("examples/ex1.xlsx", sheet_name="Sheet1")

   Unnamed: 0  a   b   c   d message
0           0  1   2   3   4   hello
1           1  5   6   7   8   world
2           2  9  10  11  12     foo

###**pandas.ExcelWriter()**

In [105]:
writer = pd.ExcelWriter("examples/ex2.xlsx")
frame.to_excel(writer, "Sheet1")
writer.close()

<ipython-input-105-6e62df696485>:2: FutureWarning: Starting with pandas version 3.0 all arguments of to_excel except for the argument 'excel_writer' will be keyword-only.
  frame.to_excel(writer, "Sheet1")

###**.to_excel()**

In [107]:
frame.to_excel("examples/ex2.xlsx")

#Using HDF5 Format
HDF5 is a respected file format intended for storing large quantities of scientific array data.
* It is available as a C library.
* The “HDF” in HDF5 stands for hierarchical data format.
* Each HDF5 file can store multiple datasets and supporting metadata.

HDF5 can be a good choice for working with datasets that don't fit into memory, as you can efficiently read and write small sections of much larger arrays.

**You must first install PyTables by installing the tables package**

In [109]:
pip install tables

Requirement already satisfied: tables in /usr/local/lib/python3.11/dist-packages (3.10.2)
Requirement already satisfied: numpy>=1.20.0 in /usr/local/lib/python3.11/dist-packages (from tables) (2.0.2)
Requirement already satisfied: numexpr>=2.6.2 in /usr/local/lib/python3.11/dist-packages (from tables) (2.10.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from tables) (24.2)
Requirement already satisfied: py-cpuinfo in /usr/local/lib/python3.11/dist-packages (from tables) (9.0.0)
Requirement already satisfied: blosc2>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from tables) (3.2.1)
Requirement already satisfied: typing-extensions>=4.4.0 in /usr/local/lib/python3.11/dist-packages (from tables) (4.13.1)
Requirement already satisfied: ndindex in /usr/local/lib/python3.11/dist-packages (from blosc2>=2.3.0->tables) (1.9.2)
Requirement already satisfied: msgpack in /usr/local/lib/python3.11/dist-packages (from blosc2>=2.3.0->tables) (1.1.0)
Requirement already satisfied: platformdirs in /usr/local/lib/python3.11/dist-packages (from blosc2>=2.3.0->tables) (4.3.7)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from blosc2>=2.3.0->tables) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->blosc2>=2.3.0->tables) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->blosc2>=2.3.0->tables) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->blosc2>=2.3.0->tables) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->blosc2>=2.3.0->tables) (2025.1.31)

###**pandas.HDFStore()**

In [111]:
import numpy as np
frame = pd.DataFrame({"a": np.random.standard_normal(100)})
store = pd.HDFStore("examples/mydata.h5")
store["obj1"] = frame
store["obj1_col"] = frame["a"]
store

<class 'pandas.io.pytables.HDFStore'>
File path: examples/mydata.h5

In [119]:
store["obj1"]

           a
0  -0.408943
1   1.154338
2  -0.577071
3  -0.569325
4  -0.647715
..       ...
95 -0.693037
96  0.819301
97  1.352346
98  0.561089
99 -0.281906

[100 rows x 1 columns]

HDFStore recibe 2 parametros, "table" and "fixed", "table" is slower but this allow query operations

##**.put()**
The put is an explicit version of the store["obj2"] = frame method but allows us to set other options like the storage format

In [122]:
store.put("obj2", frame, format="table")
store.select("obj2", where=["index >= 10 and index <= 15"])
store.close()

###**pandas.read_hdf()**

In [123]:
frame.to_hdf("examples/mydata.h5", "obj3", format="table")
pd.read_hdf("examples/mydata.h5", "obj3", where=["index < 5"])

<ipython-input-123-c8e6492ebc65>:1: FutureWarning: Starting with pandas version 3.0 all arguments of to_hdf except for the argument 'path_or_buf' will be keyword-only.
  frame.to_hdf("examples/mydata.h5", "obj3", format="table")

          a
0 -0.408943
1  1.154338
2 -0.577071
3 -0.569325
4 -0.647715

DELETE A FILE

In [124]:
import os
os.remove("examples/mydata.h5")

###**WEB APIs**

### **requests (librarie)**

In [132]:
import requests
# esta es la direccion de la API
url = "https://api.github.com/repos/pandas-dev/pandas/issues"
#aqui pide los datos y los recibe la variable
resp = requests.get(url)
#Es un metodo de errores
resp.raise_for_status()
resp

**Note**. It's a good practice to always call raise_for_status after using requests.get to check for HTTP errors.

**GET**. It is used to obtain data from a server

In [131]:
data = resp.json()
data[0]["title"]
#this error could be different because is about the real time-data

'BUG: Raise error if not busdaycalendar'

In [134]:
pd.DataFrame(data, columns=["number", "title", "labels", "state",'comments'])

,number,title,labels,state,comments
0,61250,BUG: Raise error if not busdaycalendar,[],open,0
1,61249,BLD: Try pinning ninja<1.11.1.4 for windows fr...,"[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",open,1
2,61248,BLD/CI Maybe fix Windows free-threaded?,"[{'id': 129350, 'node_id': 'MDU6TGFiZWwxMjkzNT...",open,0
3,61247,ENH: Functionality to aid with Database Imports,"[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open,0
4,61245,BUG: remove_unused_levels does not keep index ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open,1
...,...,...,...,...,...
25,61209,"ENH: Consistent NA handling in `unique()`, and...","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg=...",open,2
26,61208,BUG: OverflowError when fillna on DataFrame wi...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open,2
27,61206,BUG: round on object columns no longer raises ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open,2
28,61204,BUG: DataFrame.min with skipna=True raises Typ...,"[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ=...",open,2
29,61203,BUG: fix to_json on period,[],open,0

#**Databases**
Key Words: performance, data integrity, and scalability needs of an application

##**sqlite3**(librarie)

In [141]:
import sqlite3
#this is a sentence of SQL
query = """CREATE TABLE test1 (a VARCHAR(20), b VARCHAR(20),
c REAL, d INTEGER);"""
#This generate a conection with the database
con = sqlite3.connect("mydata.sqlite")
#this execute the sentece of SQL that create a table
con.execute(query)

**.commit()** this is lika a checkpoint that save the changes permanently

In [142]:
#just can create once table
con.commit()

In [144]:
data = [("Atlanta", "Georgia", 1.25, 6),
        ("Tallahassee", "Florida", 2.6, 3),
        ("Sacramento", "California", 1.7, 5)]
stmt = "INSERT INTO test VALUES(?, ?, ?, ?)"
con.executemany(stmt, data)

In [145]:
con.commit()

**.cursor** is an object that was crated when you execute a query

**.fetchall** Is a function that take all the rows of the query

In [146]:
cursor = con.execute("SELECT * FROM test")
# a cursor is an object that is created when execute a query
#fetchall take all the results
rows = cursor.fetchall()
rows

[('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5),
 ('Atlanta', 'Georgia', 1.25, 6),
 ('Tallahassee', 'Florida', 2.6, 3),
 ('Sacramento', 'California', 1.7, 5)]

In [147]:
cursor.description

(('a', None, None, None, None, None, None),
 ('b', None, None, None, None, None, None),
 ('c', None, None, None, None, None, None),
 ('d', None, None, None, None, None, None))

**.description**
this atribute is like in the numpyarray that describe the form of an array

**Note** that for SQLite3, the cursor description only provides column names (the other fields, which are part of Python's Database API specification, are None).

In [148]:
pd.DataFrame(rows, columns=[x[0] for x in cursor.description])

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5
3      Atlanta     Georgia  1.25  6
4  Tallahassee     Florida  2.60  3
5   Sacramento  California  1.70  5

##**.read_sql()**

In [149]:
import sqlalchemy as sqla
db = sqla.create_engine("sqlite:///mydata.sqlite")
pd.read_sql("SELECT * FROM test", db)

             a           b     c  d
0      Atlanta     Georgia  1.25  6
1  Tallahassee     Florida  2.60  3
2   Sacramento  California  1.70  5
3      Atlanta     Georgia  1.25  6
4  Tallahassee     Florida  2.60  3
5   Sacramento  California  1.70  5