# Hierarchical Indexing

Hierarchical indexing is an important feature of pandas that enables you to have multiple (two or more) index levels on an axis. Another way of thinking about it is that it provides a way for you to work with higher dimensional data in a lower dimensional form.

In [3]:
import pandas as pd
import numpy as np
data = pd.Series(np.random.uniform(size=9),
    index=[["a", "a", "a", "b", "b", "c", "c", "d", "d"],
                  [1, 2, 3, 1, 3, 1, 2, 2, 3]])
data

a  1    0.529302
   2    0.536445
   3    0.430971
b  1    0.002423
   3    0.930128
c  1    0.690970
   2    0.285386
d  2    0.069194
   3    0.598591
dtype: float64

## MultiIndex
What you’re seeing is a prettified view of a Series with a MultiIndex as its index. The “gaps” in the index display mean “use the label directly above”

In [4]:
data.index

MultiIndex([('a', 1),
            ('a', 2),
            ('a', 3),
            ('b', 1),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 2),
            ('d', 3)],
           )

With a hierarchically indexed object, so-called partial indexing is possible, enabling you to concisely select subsets of the data

In [6]:
data['b']

1    0.002423
3    0.930128
dtype: float64

In [8]:
data['b':'c']

b  1    0.002423
   3    0.930128
c  1    0.690970
   2    0.285386
dtype: float64

In [9]:
data.loc[["b", "d"]]

b  1    0.002423
   3    0.930128
d  2    0.069194
   3    0.598591
dtype: float64

Selection is even possible from an “inner” level.

In [10]:
data.loc[:, 2]

a    0.536445
c    0.285386
d    0.069194
dtype: float64

##.Unstack()
Hierarchical indexing plays an important role in reshaping data and in group-based operations like forming a pivot table. For example, you can rearrange this data into a DataFrame using its unstack method:

In [11]:
data.unstack()

          1         2         3
a  0.529302  0.536445  0.430971
b  0.002423       NaN  0.930128
c  0.690970  0.285386       NaN
d       NaN  0.069194  0.598591

###.stack()
The inverse operation of unstack is stack

In [12]:
data.unstack().stack()

a  1    0.529302
   2    0.536445
   3    0.430971
b  1    0.002423
   3    0.930128
c  1    0.690970
   2    0.285386
d  2    0.069194
   3    0.598591
dtype: float64

In [13]:
frame = pd.DataFrame(np.arange(12).reshape((4, 3)),
index=[["a", "a", "b", "b"], [1, 2, 1, 2]],
columns=[["Ohio", "Ohio", "Colorado"],
    ["Green", "Red", "Green"]])
frame

     Ohio     Colorado
    Green Red    Green
a 1     0   1        2
  2     3   4        5
b 1     6   7        8
  2     9  10       11

##.name or . names

In [14]:
frame.index.names = ["key1", "key2"]
frame.columns.names = ["state", "color"]
frame

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
     2        3   4        5
b    1        6   7        8
     2        9  10       11

##.nlevels

In [15]:
frame.index.nlevels

2

In [17]:
frame['Ohio']

color      Green  Red
key1 key2
a    1         0    1
     2         3    4
b    1         6    7
     2         9   10

In [18]:
pd.MultiIndex.from_arrays([["Ohio", "Ohio", "Colorado"],
                          ["Green", "Red", "Green"]],
                          names=["state", "color"])

MultiIndex([(    'Ohio', 'Green'),
            (    'Ohio',   'Red'),
            ('Colorado', 'Green')],
           names=['state', 'color'])

Reordering and sorting levels

swaplevel

In [20]:
frame.swaplevel("key1", "key2")

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
2    a        3   4        5
1    b        6   7        8
2    b        9  10       11

In [ ]:
sort_index

b]N]y default sorts the data lexicographically using all the index levels, but you can choose to use only a single level or a subset of levels to sort by passing the level argument. For example:

In [21]:
frame.sort_index(level=1)

state      Ohio     Colorado
color     Green Red    Green
key1 key2
a    1        0   1        2
b    1        6   7        8
a    2        3   4        5
b    2        9  10       11

In [22]:

frame.swaplevel(0, 1).sort_index(level=0)

state      Ohio     Colorado
color     Green Red    Green
key2 key1
1    a        0   1        2
     b        6   7        8
2    a        3   4        5
     b        9  10       11

Note: Data selection performance is much better on hierarchically indexed objects if the index is lexicographically sorted starting with the outermost level—that is, the result of calling sort_index(level=0) or sort_index()

##Summary Statistics by Level

In [23]:
frame.groupby(level="key2").sum()

state  Ohio     Colorado
color Green Red    Green
key2
1         6   8       10
2        12  14       16

In [24]:
frame.groupby(level="color", axis="columns").sum()

<ipython-input-24-0b8b7712eee1>:1: FutureWarning: DataFrame.groupby with axis=1 is deprecated. Do `frame.T.groupby(...)` without axis instead.
  frame.groupby(level="color", axis="columns").sum()

color      Green  Red
key1 key2
a    1         2    1
     2         8    4
b    1        14    7
     2        20   10

##Indexing with a DataFrame's columns

In [25]:
frame = pd.DataFrame({"a": range(7), "b": range(7, 0, -1),
                    "c": ["one", "one", "one", "two", "two","two", "two"],
                      "d": [0, 1, 2, 0, 1, 2, 3]})
frame

   a  b    c  d
0  0  7  one  0
1  1  6  one  1
2  2  5  one  2
3  3  4  two  0
4  4  3  two  1
5  5  2  two  2
6  6  1  two  3

##.set_index()

In [26]:
frame2 = frame.set_index(["c", "d"])
frame2

       a  b
c   d
one 0  0  7
    1  1  6
    2  2  5
two 0  3  4
    1  4  3
    2  5  2
    3  6  1

By default, the columns are removed from the DataFrame, though you can leave them in by passing drop=False to set_index

In [27]:
frame.set_index(["c", "d"], drop=False)

       a  b    c  d
c   d
one 0  0  7  one  0
    1  1  6  one  1
    2  2  5  one  2
two 0  3  4  two  0
    1  4  3  two  1
    2  5  2  two  2
    3  6  1  two  3

# Combining and merging Datasets

**pandas.merge**
Connect rows in DataFrames based on one or more keys. This will be familiar to users of SQL or other relational databases, as it implements database join operations.

**pandas.concat**
Concatenate or "stack" objects together along an axis.

**combine_first**
Splice together overlapping data to fill in missing values in one object with values from another.

##Database-Style DataFrame Joins
###pandas.merge()
Merge or join operations combine datasets by linking rows using one or more keys.

These operations are particularly important in relational databases (e.g., SQL-based).

The pandas.merge function in pandas is the main entry point for using these algorithms on your data.

In [28]:
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "a", "b"],
                    "data1": pd.Series(range(7), dtype="Int64")})
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   a      5
6   b      6

In [29]:
df2 = pd.DataFrame({"key": ["a", "b", "d"],
                    "data2": pd.Series(range(3), dtype="Int64")})
df2

  key  data2
0   a      0
1   b      1
2   d      2

In [30]:
pd.merge(df1, df2)

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [31]:
pd.merge(df1, df2, on="key")

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   a      4      0
4   a      5      0
5   b      6      1

In [32]:
df3 = pd.DataFrame({"lkey": ["b", "b", "a", "c", "a", "a", "b"],
                    "data1": pd.Series(range(7), dtype="Int64")})
df3

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    b      6

In [33]:
df4 = pd.DataFrame({"rkey": ["a", "b", "d"],
                    "data2": pd.Series(range(3), dtype="Int64")})
df4

  rkey  data2
0    a      0
1    b      1
2    d      2

In [34]:
pd.merge(df3, df4, left_on="lkey", right_on="rkey")

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    a      4    a      0
4    a      5    a      0
5    b      6    b      1

By default, pandas.merge does an "inner" join; the keys in the result are the intersection, or the common set found in both tables. Other possible options are "left", "right", and "outer". The outer join takes the union of the keys, combining the effect of applying both left and right joins
####outer

In an outer join, rows from the left or right DataFrame objects that do not match on keys in the other DataFrame will appear with NA values in the other DataFrame's columns for the nonmatching rows.

In [35]:
pd.merge(df1, df2, how="outer")

  key  data1  data2
0   a      2      0
1   a      4      0
2   a      5      0
3   b      0      1
4   b      1      1
5   b      6      1
6   c      3   <NA>
7   d   <NA>      2

In [36]:
pd.merge(df3, df4, left_on="lkey", right_on="rkey", how="outer")

  lkey  data1 rkey  data2
0    a      2    a      0
1    a      4    a      0
2    a      5    a      0
3    b      0    b      1
4    b      1    b      1
5    b      6    b      1
6    c      3  NaN   <NA>
7  NaN   <NA>    d      2

In [37]:
df1 = pd.DataFrame({"key": ["b", "b", "a", "c", "a", "b"],
                    "data1": pd.Series(range(6), dtype="Int64")})
df1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4
5   b      5

In [38]:
df2 = pd.DataFrame({"key": ["a", "b", "a", "b", "d"],
                    "data2": pd.Series(range(5), dtype="Int64")})
df2

  key  data2
0   a      0
1   b      1
2   a      2
3   b      3
4   d      4

In [40]:
pd.merge(df1, df2, on="key", how="left")

   key  data1  data2
0    b      0      1
1    b      0      3
2    b      1      1
3    b      1      3
4    a      2      0
5    a      2      2
6    c      3   <NA>
7    a      4      0
8    a      4      2
9    b      5      1
10   b      5      3

####inner

In [41]:
pd.merge(df1, df2, how="inner")

  key  data1  data2
0   b      0      1
1   b      0      3
2   b      1      1
3   b      1      3
4   a      2      0
5   a      2      2
6   a      4      0
7   a      4      2
8   b      5      1
9   b      5      3

In [42]:
left = pd.DataFrame({"key1": ["foo", "foo", "bar"],
                     "key2": ["one", "two", "one"],
                     "lval": pd.Series([1, 2, 3], dtype='Int64')})
left

  key1 key2  lval
0  foo  one     1
1  foo  two     2
2  bar  one     3

In [43]:
right = pd.DataFrame({"key1": ["foo", "foo", "bar", "bar"],
                      "key2": ["one", "one", "one", "two"],
                      "rval": pd.Series([4, 5, 6, 7], dtype='Int64')})
right

  key1 key2  rval
0  foo  one     4
1  foo  one     5
2  bar  one     6
3  bar  two     7

In [44]:
pd.merge(left, right, on=["key1", "key2"], how="outer")

  key1 key2  lval  rval
0  bar  one     3     6
1  bar  two  <NA>     7
2  foo  one     1     4
3  foo  one     1     5
4  foo  two     2  <NA>

pandas.merge has a suffixes option for specifying strings to append to overlapping names in the left and right DataFrame objects

In [45]:
 pd.merge(left, right, on="key1", suffixes=("_left", "_right"))

  key1 key2_left  lval key2_right  rval
0  foo       one     1        one     4
1  foo       one     1        one     5
2  foo       two     2        one     4
3  foo       two     2        one     5
4  bar       one     3        one     6
5  bar       one     3        two     7

##Meriging on Index
In some cases, the merge key(s) in a DataFrame will be found in its index (row labels). In this case, you can pass left_index=True or right_index=True (or both) to indicate that the index should be used as the merge key

In [46]:
left1 = pd.DataFrame({"key": ["a", "b", "a", "a", "b", "c"],
                      "value": pd.Series(range(6), dtype="Int64")})
left1

  key  value
0   a      0
1   b      1
2   a      2
3   a      3
4   b      4
5   c      5

In [47]:
right1 = pd.DataFrame({"group_val": [3.5, 7]}, index=["a", "b"])
right1

   group_val
a        3.5
b        7.0

In [48]:
pd.merge(left1, right1, left_on="key", right_index=True)

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0

In [49]:
pd.merge(left1, right1, left_on="key", right_index=True, how="outer")

  key  value  group_val
0   a      0        3.5
2   a      2        3.5
3   a      3        3.5
1   b      1        7.0
4   b      4        7.0
5   c      5        NaN

In [50]:
lefth = pd.DataFrame({"key1": ["Ohio", "Ohio", "Ohio","Nevada", "Nevada"],
                      "key2": [2000, 2001, 2002, 2001, 2002],
                      "data": pd.Series(range(5), dtype="Int64")})
lefth

     key1  key2  data
0    Ohio  2000     0
1    Ohio  2001     1
2    Ohio  2002     2
3  Nevada  2001     3
4  Nevada  2002     4

In [51]:
righth_index = pd.MultiIndex.from_arrays(
    [["Nevada", "Nevada", "Ohio", "Ohio", "Ohio", "Ohio"],
    [2001, 2000, 2000, 2000, 2001, 2002]])
righth_index

MultiIndex([('Nevada', 2001),
            ('Nevada', 2000),
            (  'Ohio', 2000),
            (  'Ohio', 2000),
            (  'Ohio', 2001),
            (  'Ohio', 2002)],
           )

In [53]:
righth = pd.DataFrame(
    {"event1": pd.Series([0, 2, 4, 6, 8, 10], dtype="Int64", index=righth_index),
     "event2": pd.Series([1, 3, 5, 7, 9, 11], dtype="Int64",index=righth_index)})
righth

             event1  event2
Nevada 2001       0       1
       2000       2       3
Ohio   2000       4       5
       2000       6       7
       2001       8       9
       2002      10      11

In [54]:
pd.merge(lefth, righth, left_on=["key1", "key2"], right_index=True)

     key1  key2  data  event1  event2
0    Ohio  2000     0       4       5
0    Ohio  2000     0       6       7
1    Ohio  2001     1       8       9
2    Ohio  2002     2      10      11
3  Nevada  2001     3       0       1

In [55]:
pd.merge(lefth, righth, left_on=["key1", "key2"], right_index=True, how="outer")

     key1  key2  data  event1  event2
4  Nevada  2000  <NA>       2       3
3  Nevada  2001     3       0       1
4  Nevada  2002     4    <NA>    <NA>
0    Ohio  2000     0       4       5
0    Ohio  2000     0       6       7
1    Ohio  2001     1       8       9
2    Ohio  2002     2      10      11

In [56]:
left2 = pd.DataFrame([[1., 2.], [3., 4.], [5., 6.]],
                     index=["a", "c", "e"],
                     columns=["Ohio", "Nevada"]).astype("Int64")
left2

   Ohio  Nevada
a     1       2
c     3       4
e     5       6

In [57]:
right2 = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [13, 14]],
                      index=["b", "c", "d", "e"],
                      columns=["Missouri", "Alabama"]).astype("Int64")
right2

   Missouri  Alabama
b         7        8
c         9       10
d        11       12
e        13       14

In [58]:
pd.merge(left2, right2, how="outer", left_index=True, right_index=True)

   Ohio  Nevada  Missouri  Alabama
a     1       2      <NA>     <NA>
b  <NA>    <NA>         7        8
c     3       4         9       10
d  <NA>    <NA>        11       12
e     5       6        13       14

###.join()
DataFrame has a join instance method to simplify merging by index. It can also be used to combine many DataFrame objects having the same or similar indexes but nonoverlapping columns.

In [59]:
left2.join(right2, how="outer")

   Ohio  Nevada  Missouri  Alabama
a     1       2      <NA>     <NA>
b  <NA>    <NA>         7        8
c     3       4         9       10
d  <NA>    <NA>        11       12
e     5       6        13       14

In [60]:
left1.join(right1, on="key")

  key  value  group_val
0   a      0        3.5
1   b      1        7.0
2   a      2        3.5
3   a      3        3.5
4   b      4        7.0
5   c      5        NaN

Compared with pandas.merge, DataFrame’s join method performs a left join on the join keys by default. It also supports joining the index of the passed DataFrame on one of the columns of the calling DataFrame

In [61]:
another = pd.DataFrame([[7., 8.], [9., 10.], [11., 12.], [16., 17.]],
                       index=["a", "c", "e", "f"],
                       columns=["New York", "Oregon"])
another

   New York  Oregon
a       7.0     8.0
c       9.0    10.0
e      11.0    12.0
f      16.0    17.0

In [62]:
left2.join([right2, another])

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2      <NA>     <NA>       7.0     8.0
c     3       4         9       10       9.0    10.0
e     5       6        13       14      11.0    12.0

In [63]:
left2.join([right2, another], how="outer")

   Ohio  Nevada  Missouri  Alabama  New York  Oregon
a     1       2      <NA>     <NA>       7.0     8.0
c     3       4         9       10       9.0    10.0
e     5       6        13       14      11.0    12.0
b  <NA>    <NA>         7        8       NaN     NaN
d  <NA>    <NA>        11       12       NaN     NaN
f  <NA>    <NA>      <NA>     <NA>      16.0    17.0

##Concatenating Along an Axis
key word: stacking

###numpy.concatenate()

In [64]:
arr = np.arange(12).reshape((3, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [65]:
np.concatenate([arr, arr], axis=1)

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

If the objects are indexed differently on the other axes, should we combine the distinct elements in these axes or use only the values in common?

Do the concatenated chunks of data need to be identifiable as such in the resulting object?

Does the "concatenation axis" contain data that needs to be preserved? In many cases, the default integer labels in a DataFrame are best discarded during concatenation.

In [66]:
s1 = pd.Series([0, 1], index=["a", "b"], dtype="Int64")
s1

a    0
b    1
dtype: Int64

In [67]:
s2 = pd.Series([2, 3, 4], index=["c", "d", "e"], dtype="Int64")
s2

c    2
d    3
e    4
dtype: Int64

In [68]:
s3 = pd.Series([5, 6], index=["f", "g"], dtype="Int64")
s3

f    5
g    6
dtype: Int64

###pandas.concat()

In [69]:
pd.concat([s1, s2, s3])

a    0
b    1
c    2
d    3
e    4
f    5
g    6
dtype: Int64

In [70]:
pd.concat([s1, s2, s3], axis="columns")

      0     1     2
a     0  <NA>  <NA>
b     1  <NA>  <NA>
c  <NA>     2  <NA>
d  <NA>     3  <NA>
e  <NA>     4  <NA>
f  <NA>  <NA>     5
g  <NA>  <NA>     6

In [71]:
s4 = pd.concat([s1, s3])
s4

a    0
b    1
f    5
g    6
dtype: Int64

In [72]:
pd.concat([s1, s4], axis="columns")

      0  1
a     0  0
b     1  1
f  <NA>  5
g  <NA>  6

In [73]:
pd.concat([s1, s4], axis="columns", join="inner")

   0  1
a  0  0
b  1  1

In [74]:
result = pd.concat([s1, s1, s3], keys=["one", "two", "three"])
result

one    a    0
       b    1
two    a    0
       b    1
three  f    5
       g    6
dtype: Int64

In [75]:
result.unstack()

          a     b     f     g
one       0     1  <NA>  <NA>
two       0     1  <NA>  <NA>
three  <NA>  <NA>     5     6

In [76]:
pd.concat([s1, s2, s3], axis="columns", keys=["one", "two", "three"])

    one   two  three
a     0  <NA>   <NA>
b     1  <NA>   <NA>
c  <NA>     2   <NA>
d  <NA>     3   <NA>
e  <NA>     4   <NA>
f  <NA>  <NA>      5
g  <NA>  <NA>      6

In [77]:
df1 = pd.DataFrame(np.arange(6).reshape(3, 2), index=["a", "b", "c"],
                   columns=["one", "two"])
df1

   one  two
a    0    1
b    2    3
c    4    5

In [78]:
df2 = pd.DataFrame(5 + np.arange(4).reshape(2, 2), index=["a", "c"],
                   columns=["three", "four"])
df2

   three  four
a      5     6
c      7     8

In [79]:
pd.concat([df1, df2], axis="columns", keys=["level1", "level2"])

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [80]:
pd.concat({"level1": df1, "level2": df2}, axis="columns")

  level1     level2
     one two  three four
a      0   1    5.0  6.0
b      2   3    NaN  NaN
c      4   5    7.0  8.0

In [81]:
pd.concat([df1, df2], axis="columns", keys=["level1", "level2"],
          names=["upper", "lower"])

upper level1     level2
lower    one two  three four
a          0   1    5.0  6.0
b          2   3    NaN  NaN
c          4   5    7.0  8.0

In [82]:
df1 = pd.DataFrame(np.random.standard_normal((3, 4)),
                   columns=["a", "b", "c", "d"])
df1

          a         b         c         d
0 -1.472391 -0.823693 -0.462901 -1.172345
1  0.368919 -0.407496  0.738962 -0.567473
2  0.405781  1.071539 -1.087255  0.423632

In [83]:
df2 = pd.DataFrame(np.random.standard_normal((2, 3)),
                   columns=["b", "d", "a"])
df2

          b         d         a
0 -0.069735  0.754364  1.824685
1  0.103309 -1.245993 -0.349764

you can pass ignore_index=True, which discards the indexes from each DataFrame and concatenates the data in the columns only, assigning a new default index

In [84]:
pd.concat([df1, df2], ignore_index=True)

          a         b         c         d
0 -1.472391 -0.823693 -0.462901 -1.172345
1  0.368919 -0.407496  0.738962 -0.567473
2  0.405781  1.071539 -1.087255  0.423632
3  1.824685 -0.069735       NaN  0.754364
4 -0.349764  0.103309       NaN -1.245993

## Combining Data with Overlap

In [85]:
a = pd.Series([np.nan, 2.5, 0.0, 3.5, 4.5, np.nan],
              index=["f", "e", "d", "c", "b", "a"])
a

f    NaN
e    2.5
d    0.0
c    3.5
b    4.5
a    NaN
dtype: float64

In [86]:
b = pd.Series([0., np.nan, 2., np.nan, np.nan, 5.],
              index=["a", "b", "c", "d", "e", "f"])
b

a    0.0
b    NaN
c    2.0
d    NaN
e    NaN
f    5.0
dtype: float64

###numpy.where()
Using numpy.where does not check whether the index labels are aligned or not (and does not even require the objects to be the same length), so if you want to line up values by index, use the Series combine_first method

In [87]:
np.where(pd.isna(a), b, a)

array([0. , 2.5, 0. , 3.5, 4.5, 5. ])

###.combine_fist()
combine_first does the same thing column by column, so you can think of it as “patching” missing data in the calling object with data from the object you pass

In [88]:
a.combine_first(b)

a    0.0
b    4.5
c    3.5
d    0.0
e    2.5
f    5.0
dtype: float64

In [89]:
df1 = pd.DataFrame({"a": [1., np.nan, 5., np.nan],
                    "b": [np.nan, 2., np.nan, 6.],
                    "c": range(2, 18, 4)})
df1

     a    b   c
0  1.0  NaN   2
1  NaN  2.0   6
2  5.0  NaN  10
3  NaN  6.0  14

In [90]:
df2 = pd.DataFrame({"a": [5., 4., np.nan, 3., 7.],
                    "b": [np.nan, 3., 4., 6., 8.]})
df2

     a    b
0  5.0  NaN
1  4.0  3.0
2  NaN  4.0
3  3.0  6.0
4  7.0  8.0

In [91]:
df1.combine_first(df2)

     a    b     c
0  1.0  NaN   2.0
1  4.0  2.0   6.0
2  5.0  4.0  10.0
3  3.0  6.0  14.0
4  7.0  8.0   NaN

#Reshaping and Pivoting
There are a number of basic operations for rearranging tabular data. These are referred to as reshape or pivot operations.

## Reshaping with Hierarchical Indexing
**stack**
This “rotates” or pivots from the columns in the data to the rows.

**unstack**
This pivots from the rows into the columns.

In [92]:
data = pd.DataFrame(np.arange(6).reshape((2, 3)),
                    index=pd.Index(["Ohio", "Colorado"], name="state"),
                    columns=pd.Index(["one", "two", "three"],
                    name="number"))
data

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

###.stack()
Using the stack method on this data pivots the columns into the rows, producing a Series

In [93]:
result = data.stack()
result

state     number
Ohio      one       0
          two       1
          three     2
Colorado  one       3
          two       4
          three     5
dtype: int64

###.unstack()
From a hierarchically indexed Series, you can rearrange the data back into a DataFrame with unstack

In [94]:
result.unstack()

number    one  two  three
state
Ohio        0    1      2
Colorado    3    4      5

In [95]:
result.unstack(level=0)

state   Ohio  Colorado
number
one        0         3
two        1         4
three      2         5

In [96]:
result.unstack(level="state")

state   Ohio  Colorado
number
one        0         3
two        1         4
three      2         5

In [97]:
s1 = pd.Series([0, 1, 2, 3], index=["a", "b", "c", "d"], dtype="Int64")
s1

a    0
b    1
c    2
d    3
dtype: Int64

In [98]:
s2 = pd.Series([4, 5, 6], index=["c", "d", "e"], dtype="Int64")
s2

c    4
d    5
e    6
dtype: Int64

In [99]:
data2 = pd.concat([s1, s2], keys=["one", "two"])
data2

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [100]:
data2.unstack()

        a     b  c  d     e
one     0     1  2  3  <NA>
two  <NA>  <NA>  4  5     6

In [101]:
data2.unstack().stack()

one  a    0
     b    1
     c    2
     d    3
two  c    4
     d    5
     e    6
dtype: Int64

In [102]:
data2.unstack().stack(dropna=False)

<ipython-input-102-03741fdba496>:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  data2.unstack().stack(dropna=False)

one  a       0
     b       1
     c       2
     d       3
     e    <NA>
two  a    <NA>
     b    <NA>
     c       4
     d       5
     e       6
dtype: Int64

In [103]:
df = pd.DataFrame({"left": result, "right": result + 5},
                  columns=pd.Index(["left", "right"], name="side"))
df

side             left  right
state    number
Ohio     one        0      5
         two        1      6
         three      2      7
Colorado one        3      8
         two        4      9
         three      5     10

In [104]:
df.unstack(level="state")

side   left          right
state  Ohio Colorado  Ohio Colorado
number
one       0        3     5        8
two       1        4     6        9
three     2        5     7       10

In [105]:
df.unstack(level="state").stack(level="side")

<ipython-input-105-2b74f4751ce1>:1: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  df.unstack(level="state").stack(level="side")

state         Ohio  Colorado
number side
one    left      0         3
       right     5         8
two    left      1         4
       right     6         9
three  left      2         5
       right     7        10

##Pivoting Long to wide
A common way to store multiple time series in databases and CSV files is what is sometimes called long or stacked format. In this format, individual values are represented by a single row in a table rather than multiple values per row

In [106]:
data = pd.read_csv("examples/macrodata.csv")
data = data.loc[:, ["year", "quarter", "realgdp", "infl", "unemp"]]
data.head()

   year  quarter   realgdp  infl  unemp
0  1959        1  2710.349  0.00    5.8
1  1959        2  2778.801  2.34    5.1
2  1959        3  2775.488  2.74    5.3
3  1959        4  2785.204  0.27    5.6
4  1960        1  2847.699  2.31    5.2

###pandas.PeriodIndex()
(which represents time intervals rather than points in time)

In [107]:
periods = pd.PeriodIndex(year=data.pop("year"),
                         quarter=data.pop("quarter"),
                         name="date")
periods

<ipython-input-107-8a5eb0706c33>:1: FutureWarning: Constructing PeriodIndex from fields is deprecated. Use PeriodIndex.from_fields instead.
  periods = pd.PeriodIndex(year=data.pop("year"),

PeriodIndex(['1959Q1', '1959Q2', '1959Q3', '1959Q4', '1960Q1', '1960Q2',
             '1960Q3', '1960Q4', '1961Q1', '1961Q2',
             ...
             '2007Q2', '2007Q3', '2007Q4', '2008Q1', '2008Q2', '2008Q3',
             '2008Q4', '2009Q1', '2009Q2', '2009Q3'],
            dtype='period[Q-DEC]', name='date', length=203)

In [108]:
data.index = periods.to_timestamp("D")
data.head()

             realgdp  infl  unemp
date
1959-01-01  2710.349  0.00    5.8
1959-04-01  2778.801  2.34    5.1
1959-07-01  2775.488  2.74    5.3
1959-10-01  2785.204  0.27    5.6
1960-01-01  2847.699  2.31    5.2

In [109]:
data = data.reindex(columns=["realgdp", "infl", "unemp"])
data.columns.name = "item"
data.head()

item         realgdp  infl  unemp
date
1959-01-01  2710.349  0.00    5.8
1959-04-01  2778.801  2.34    5.1
1959-07-01  2775.488  2.74    5.3
1959-10-01  2785.204  0.27    5.6
1960-01-01  2847.699  2.31    5.2

###.reset_index()

In [111]:
long_data = (data.stack().reset_index().rename(columns={0: "value"}))
long_data[:10]

        date     item     value
0 1959-01-01  realgdp  2710.349
1 1959-01-01     infl     0.000
2 1959-01-01    unemp     5.800
3 1959-04-01  realgdp  2778.801
4 1959-04-01     infl     2.340
5 1959-04-01    unemp     5.100
6 1959-07-01  realgdp  2775.488
7 1959-07-01     infl     2.740
8 1959-07-01    unemp     5.300
9 1959-10-01  realgdp  2785.204

Data is often stored in relational SQL databases using a fixed schema (defined columns and types), which makes it easy to add new item values over time. In such tables, columns like date and item usually act as primary keys, helping maintain data integrity and enabling efficient joins. However, working with data in this long format can be harder for analysis. In those cases, you might prefer a pivoted format—a table where each unique item becomes its own column, and rows are indexed by date. You can do this in pandas using the .pivot() method

In [112]:
pivoted = long_data.pivot(index="date", columns="item", values="value")
pivoted.head()

item        infl   realgdp  unemp
date
1959-01-01  0.00  2710.349    5.8
1959-04-01  2.34  2778.801    5.1
1959-07-01  2.74  2775.488    5.3
1959-10-01  0.27  2785.204    5.6
1960-01-01  2.31  2847.699    5.2

In [115]:
long_data["value2"] = np.random.standard_normal(len(long_data))
long_data[:10]

        date     item     value    value2
0 1959-01-01  realgdp  2710.349 -1.406706
1 1959-01-01     infl     0.000 -0.148795
2 1959-01-01    unemp     5.800 -1.433857
3 1959-04-01  realgdp  2778.801 -0.117679
4 1959-04-01     infl     2.340 -0.124515
5 1959-04-01    unemp     5.100  0.540161
6 1959-07-01  realgdp  2775.488 -0.646710
7 1959-07-01     infl     2.740  0.380604
8 1959-07-01    unemp     5.300 -1.775317
9 1959-10-01  realgdp  2785.204 -2.476310

Note that pivot is equivalent to creating a hierarchical index using set_index followed by a call to unstack

In [117]:
pivoted = long_data.pivot(index="date", columns="item")
pivoted.head()

           value                    value2
item        infl   realgdp unemp      infl   realgdp     unemp
date
1959-01-01  0.00  2710.349   5.8 -0.148795 -1.406706 -1.433857
1959-04-01  2.34  2778.801   5.1 -0.124515 -0.117679  0.540161
1959-07-01  2.74  2775.488   5.3  0.380604 -0.646710 -1.775317
1959-10-01  0.27  2785.204   5.6 -0.003622 -2.476310 -0.697914
1960-01-01  2.31  2847.699   5.2  0.559595 -0.491738  0.960274

In [118]:
pivoted["value"].head()

item        infl   realgdp  unemp
date
1959-01-01  0.00  2710.349    5.8
1959-04-01  2.34  2778.801    5.1
1959-07-01  2.74  2775.488    5.3
1959-10-01  0.27  2785.204    5.6
1960-01-01  2.31  2847.699    5.2

In [119]:
unstacked = long_data.set_index(["date", "item"]).unstack(level="item")
unstacked.head()

           value                    value2
item        infl   realgdp unemp      infl   realgdp     unemp
date
1959-01-01  0.00  2710.349   5.8 -0.148795 -1.406706 -1.433857
1959-04-01  2.34  2778.801   5.1 -0.124515 -0.117679  0.540161
1959-07-01  2.74  2775.488   5.3  0.380604 -0.646710 -1.775317
1959-10-01  0.27  2785.204   5.6 -0.003622 -2.476310 -0.697914
1960-01-01  2.31  2847.699   5.2  0.559595 -0.491738  0.960274

##Pivoting Wide to Long

In [120]:
df = pd.DataFrame({"key": ["foo", "bar", "baz"],
                   "A": [1, 2, 3],
                   "B": [4, 5, 6],
                   "C": [7, 8, 9]})
df

   key  A  B  C
0  foo  1  4  7
1  bar  2  5  8
2  baz  3  6  9

###pandas.melt()
When using pandas.melt, we must indicate which columns (if any) are group indicators.

In [121]:
melted = pd.melt(df, id_vars="key")
melted

   key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6
6  foo        C      7
7  bar        C      8
8  baz        C      9

###.pivot()
we can reshape back to the original layout

In [122]:
reshaped = melted.pivot(index="key", columns="variable",
                        values="value")
reshaped

variable  A  B  C
key
bar       2  5  8
baz       3  6  9
foo       1  4  7

In [123]:
reshaped.reset_index()

variable  key  A  B  C
0         bar  2  5  8
1         baz  3  6  9
2         foo  1  4  7

In [124]:
pd.melt(df, id_vars="key", value_vars=["A", "B"])

   key variable  value
0  foo        A      1
1  bar        A      2
2  baz        A      3
3  foo        B      4
4  bar        B      5
5  baz        B      6

In [125]:
pd.melt(df, value_vars=["A", "B", "C"])

  variable  value
0        A      1
1        A      2
2        A      3
3        B      4
4        B      5
5        B      6
6        C      7
7        C      8
8        C      9

In [126]:
pd.melt(df, value_vars=["key", "A", "B"])

  variable value
0      key   foo
1      key   bar
2      key   baz
3        A     1
4        A     2
5        A     3
6        B     4
7        B     5
8        B     6